apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-app
  namespace: argocd  # Argo CD 설치 namespace
spec:
  project: default
  source:
    repoURL: https://github.com/endermaru/spring-app-gitops.git
    targetRevision: HEAD
    path: base        # deployment 등이 있는 디렉토리
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
