# root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:                                  
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/endermaru/spring-app-gitops
    targetRevision: main
    path: apps                 # 여러 Child apps의 yaml들이 있는 디렉토리
    directory:
      recurse: false           # apps/ 디렉토리만 읽고 하위 디렉토리는 무시
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd          # root-app 자체는 argocd에 생성
  syncPolicy:
    automated:
      prune: true
      selfHeal: true