apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spring-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: spring-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: myapp
