apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: endermaru/22-5-team1-server
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
            name: spring-secret
          
---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
    - port: 8080
      targetPort: 8080
