apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        vault.hashicorp.com/agent-inject: "true" # Vault Agent Injector를 사용하면, 
        vault.hashicorp.com/role: {{ .Values.vault.role }} # pod가 뜰 때 Vault 인증을 하고, 주기적으로 토큰을 자동 갱신
        vault.hashicorp.com/auth-type: "kubernetes"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-token-ttl: "24h"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: spring
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: local
          envFrom:
            - secretRef:
               name: {{ .Values.secret.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 8080
      targetPort: 8080
